# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ef6d3f8875110920e93050a8fc9c19a5fa004b1d6e618b690da9da7cbe31fb63287ee45f56d19979fb4ef31ab340e3c4545dae5f5cb588e8ea080f3584b02f

test:
  secret_key_base: a4aaae4aa920e08b26817f298a93e9624dc0217026512161e233e29d2bf43e2a6cd8bce5206f9c93ab6342328ba037ffeecde7b07ac0efda274469d614e7f355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
